vim.opt.autoindent=true
vim.opt.smartindent=true
vim.opt.expandtab=true
vim.opt.tabstop=4
vim.opt.shiftwidth=4
vim.opt.number=true
vim.opt.relativenumber=true
vim.opt.termguicolors=true
require("config.lazy")
